spring:
    profiles:
        active: prod
#    datasource:
#        driver-class-name: org.h2.Driver
#        password: sa
#        url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
#        username: sa
#    h2:
#        console:
#            path: /h2-console
#            settings:
#                trace: false
#                web-allow-others: false
#    jpa:
#        database-platform: org.hibernate.dialect.H2Dialect
#        properties:
#            hibernate:
#                format_sql: true
    liquibase:
        enabled: true
        change-log: classpath:db/changelog/changelog.sql
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 51MB
    mail:
        host: 10.73.0.11
        port: 25
        username: 0815
        password: kdlwm89o
        properties:
            mail:
                smtp:
                    auth: true
                    starttls.enable: true
    task:
        scheduling:
            pool:
                size: 1
app:
    api:
        version: v1
    mail:
        from: 0815@073.pfr.gov.ru
    security:
        key: bc26ceda53f96c1ef58ce64b927ca3d58df8031fec526af8ce23a81d7ce961ad
        credentials: KwT6h7tntpi3YBwIh2NPvOHnVvoEO369FcKo7nA2yglyyydn0encrTHYQqsLIOBA
    message:
        showing_time: 36000
    tasks:
        enable: true
